### ISSUE TITLE
JS totally borked

### ISSUE THREAD

**Issue by dirtycajunrice** [tamburra/organizrv2-titanembeds#1]
Preface: im on v2 of org.

Whats the purpose of 
```
var orgTabName = "Discord"; 
```
being definable if
```
if (name === 'Discord') {
```
only listens for discord?

In addition... when the JS is enabled, no other tabs work either. I assume this is because you have completely taken over the tabActions() function which has no rules for anything other than your tab.

**Comment by kdoubledubs** [comment]
Please use new code.  Has been cleaned up.  Working now.

**Comment by dirtycajunrice** [comment]
I see that. Wonderful. I do suggest that you add (until org fixes the order of operations) to the comments that they need to be on the newest dev version for it to render *almost* in order, and that it cannot be the default loaded/nor pre-loaded or the js will render after the page has loaded.

**Comment by kdoubledubs** [comment]
Done.
